@startuml
actor User
participant VendorSite 
participant MobileServer
User -> VendorSite: Access home page
activate VendorSite
VendorSite -> MobileServer: GET api/vendors/{vendor_name}
activate MobileServer
VendorSite <-- MobileServer: Vendor ID
deactivate MobileServer
VendorSite -> MobileServer: GET api/products/{vendor_id}
activate MobileServer
VendorSite <-- MobileServer: Products list of that vendor
deactivate MobileServer
User <-- VendorSite: Redirect filtered product page
User -> VendorSite: Press "checkout" button
VendorSite -> MobileServer: POST api/orders
activate MobileServer
VendorSite <-- MobileServer: Order info
deactivate MobileServer 
User <-- VendorSite: Redirect to checkout page
User -> VendorSite: Fill in shipping address, \npayment info, shipping info, \nthen press "continue to payment"
VendorSite -> MobileServer: POST api/checkout
activate MobileServer
VendorSite <-- MobileServer: Order updated with \nshipping and payment info
deactivate MobileServer
User <-- VendorSite: Redirect to payment page
User -> VendorSite: Press place order
VendorSite -> MobileServer: POST api/order/pay
activate MobileServer
VendorSite <-- MobileServer: Payment process info \n(status and redirectURL)
deactivate MobileServer
User <-- VendorSite: Redirect payment successful page
deactivate MobileServer
deactivate VendorSite
@enduml